-- ════════════════════════════════════════════════════════════
-- Ce fichier est conservé pour référence historique uniquement.
-- Le schéma actuel est dans :
--
--   supabase/migrations/001_initial_schema.sql
--
-- Pour appliquer la migration :
--   → Supabase Dashboard : SQL Editor → coller le contenu de la migration
--   → Supabase CLI       : supabase db push
-- ════════════════════════════════════════════════════════════
